package com.model;
// Generated Jul 12, 2019 12:14:04 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CtLoi generated by hbm2java
 */
@Entity
@Table(name="CT_Loi"
    ,schema="dbo"
    ,catalog="Libary"
)
public class CtLoi  implements java.io.Serializable {


     private int maCtl;
     private CtPhieumuon ctPhieumuon;
     private Loi loi;
     private Integer soTien;

    public CtLoi() {
    }

	
    public CtLoi(int maCtl) {
        this.maCtl = maCtl;
    }
    public CtLoi(int maCtl, CtPhieumuon ctPhieumuon, Loi loi, Integer soTien) {
       this.maCtl = maCtl;
       this.ctPhieumuon = ctPhieumuon;
       this.loi = loi;
       this.soTien = soTien;
    }
   
     @Id 

    
    @Column(name="maCTL", unique=true, nullable=false)
    public int getMaCtl() {
        return this.maCtl;
    }
    
    public void setMaCtl(int maCtl) {
        this.maCtl = maCtl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maCTPM")
    public CtPhieumuon getCtPhieumuon() {
        return this.ctPhieumuon;
    }
    
    public void setCtPhieumuon(CtPhieumuon ctPhieumuon) {
        this.ctPhieumuon = ctPhieumuon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maLoi")
    public Loi getLoi() {
        return this.loi;
    }
    
    public void setLoi(Loi loi) {
        this.loi = loi;
    }

    
    @Column(name="soTien")
    public Integer getSoTien() {
        return this.soTien;
    }
    
    public void setSoTien(Integer soTien) {
        this.soTien = soTien;
    }




}


