package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CtLoi generated by hbm2java
 */
@Entity
@Table(name="CT_Loi"
    ,schema="dbo"
    ,catalog="libary"
)
public class CtLoi  implements java.io.Serializable {


     private int maCtl;
     private DauSachCtpm dauSachCtpm;
     private Loi loi;

    public CtLoi() {
    }

	
    public CtLoi(int maCtl) {
        this.maCtl = maCtl;
    }
    public CtLoi(int maCtl, DauSachCtpm dauSachCtpm, Loi loi) {
       this.maCtl = maCtl;
       this.dauSachCtpm = dauSachCtpm;
       this.loi = loi;
    }
   
    @Id 
    @Column(name="maCTL", unique=true, nullable=false)
    public int getMaCtl() {
        return this.maCtl;
    }
    
    public void setMaCtl(int maCtl) {
        this.maCtl = maCtl;
    }


    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ma_DauSach_CTPM", referencedColumnName="id", insertable=false, updatable=false) 
    public DauSachCtpm getDauSachCtpm() {
        return this.dauSachCtpm;
    }
    
    public void setDauSachCtpm(DauSachCtpm dauSachCtpm) {
        this.dauSachCtpm = dauSachCtpm;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maLoi")
    public Loi getLoi() {
        return this.loi;
    }
    
    public void setLoi(Loi loi) {
        this.loi = loi;
    }




}


