package com.model;
// Generated Jul 17, 2019 3:18:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CtPhieumuon generated by hbm2java
 */
@Entity
@Table(name="CT_PHIEUMUON"
    ,schema="dbo"
    ,catalog="Libary"
)
public class CtPhieumuon  implements java.io.Serializable {


     private int maCtpm;
     private PhieuMuon phieuMuon;
     private Sach sach;
     private String ghiChu;
     private String ngayTra;
     private Set<CtLoi> ctLois = new HashSet<CtLoi>(0);

    public CtPhieumuon() {
    }

	
    public CtPhieumuon(int maCtpm) {
        this.maCtpm = maCtpm;
    }
    public CtPhieumuon(int maCtpm, PhieuMuon phieuMuon, Sach sach, String ghiChu, String ngayTra, Set<CtLoi> ctLois) {
       this.maCtpm = maCtpm;
       this.phieuMuon = phieuMuon;
       this.sach = sach;
       this.ghiChu = ghiChu;
       this.ngayTra = ngayTra;
       this.ctLois = ctLois;
    }
   
     @Id 

    
    @Column(name="maCTPM", unique=true, nullable=false)
    public int getMaCtpm() {
        return this.maCtpm;
    }
    
    public void setMaCtpm(int maCtpm) {
        this.maCtpm = maCtpm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maPM")
    public PhieuMuon getPhieuMuon() {
        return this.phieuMuon;
    }
    
    public void setPhieuMuon(PhieuMuon phieuMuon) {
        this.phieuMuon = phieuMuon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maSach")
    public Sach getSach() {
        return this.sach;
    }
    
    public void setSach(Sach sach) {
        this.sach = sach;
    }

    
    @Column(name="ghiChu", length=100)
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }

    
    @Column(name="ngayTra", length=10)
    public String getNgayTra() {
        return this.ngayTra;
    }
    
    public void setNgayTra(String ngayTra) {
        this.ngayTra = ngayTra;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctPhieumuon")
    public Set<CtLoi> getCtLois() {
        return this.ctLois;
    }
    
    public void setCtLois(Set<CtLoi> ctLois) {
        this.ctLois = ctLois;
    }




}


