package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CtPhieuNhap generated by hbm2java
 */
@Entity
@Table(name="CT_PhieuNhap"
    ,schema="dbo"
    ,catalog="libary"
)
public class CtPhieuNhap  implements java.io.Serializable {


     private int maCtpn;
     private PhieuNhap phieuNhap;
     private Sach sach;
     private Integer soLuong;

    public CtPhieuNhap() {
    }

	
    public CtPhieuNhap(int maCtpn) {
        this.maCtpn = maCtpn;
    }
    public CtPhieuNhap(int maCtpn, PhieuNhap phieuNhap, Sach sach, Integer soLuong) {
       this.maCtpn = maCtpn;
       this.phieuNhap = phieuNhap;
       this.sach = sach;
       this.soLuong = soLuong;
    }
   
     @Id 

    
    @Column(name="maCTPN", unique=true, nullable=false)
    public int getMaCtpn() {
        return this.maCtpn;
    }
    
    public void setMaCtpn(int maCtpn) {
        this.maCtpn = maCtpn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maPhieuNhap")
    public PhieuNhap getPhieuNhap() {
        return this.phieuNhap;
    }
    
    public void setPhieuNhap(PhieuNhap phieuNhap) {
        this.phieuNhap = phieuNhap;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maSach")
    public Sach getSach() {
        return this.sach;
    }
    
    public void setSach(Sach sach) {
        this.sach = sach;
    }

    
    @Column(name="soLuong")
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }




}


