package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DanhMuc generated by hbm2java
 */
@Entity
@Table(name="danhMuc"
    ,schema="dbo"
    ,catalog="libary"
    , uniqueConstraints = @UniqueConstraint(columnNames="url") 
)
public class DanhMuc  implements java.io.Serializable {


     private int idDanhMuc;
     private String tenDanhMuc;
     private String url;
     private Set<TheLoai> theLoais = new HashSet<TheLoai>(0);

    public DanhMuc() {
    }

	
    public DanhMuc(int idDanhMuc) {
        this.idDanhMuc = idDanhMuc;
    }
    public DanhMuc(int idDanhMuc, String tenDanhMuc, String url, Set<TheLoai> theLoais) {
       this.idDanhMuc = idDanhMuc;
       this.tenDanhMuc = tenDanhMuc;
       this.url = url;
       this.theLoais = theLoais;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_danhMuc", unique=true, nullable=false)
    public int getIdDanhMuc() {
        return this.idDanhMuc;
    }
    
    public void setIdDanhMuc(int idDanhMuc) {
        this.idDanhMuc = idDanhMuc;
    }

    
    @Column(name="tenDanhMuc", length=50)
    public String getTenDanhMuc() {
        return this.tenDanhMuc;
    }
    
    public void setTenDanhMuc(String tenDanhMuc) {
        this.tenDanhMuc = tenDanhMuc;
    }

    
    @Column(name="url", unique=true, length=50)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="danhMuc")
    public Set<TheLoai> getTheLoais() {
        return this.theLoais;
    }
    
    public void setTheLoais(Set<TheLoai> theLoais) {
        this.theLoais = theLoais;
    }




}


