package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DauSachCtpm generated by hbm2java
 */
@Entity
@Table(name="DauSach_CTPM"
    ,schema="dbo"
    ,catalog="Libary"
)
public class DauSachCtpm  implements java.io.Serializable {


     private DauSachCtpmId id;
     private DauSach dauSach;
     private Set<CtLoi> ctLois = new HashSet<CtLoi>(0);

    public DauSachCtpm() {
    }

	
    public DauSachCtpm(DauSachCtpmId id, DauSach dauSach) {
        this.id = id;
        this.dauSach = dauSach;
    }
    public DauSachCtpm(DauSachCtpmId id, DauSach dauSach, Set<CtLoi> ctLois) {
       this.id = id;
       this.dauSach = dauSach;
       this.ctLois = ctLois;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="maCtpm", column=@Column(name="maCTPM", nullable=false) ), 
        @AttributeOverride(name="barcode", column=@Column(name="barcode", nullable=false, length=10) ) } )
    public DauSachCtpmId getId() {
        return this.id;
    }
    
    public void setId(DauSachCtpmId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="barcode", nullable=false, insertable=false, updatable=false)
    public DauSach getDauSach() {
        return this.dauSach;
    }
    
    public void setDauSach(DauSach dauSach) {
        this.dauSach = dauSach;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dauSachCtpm")
    public Set<CtLoi> getCtLois() {
        return this.ctLois;
    }
    
    public void setCtLois(Set<CtLoi> ctLois) {
        this.ctLois = ctLois;
    }




}


