package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DauSachCtpm generated by hbm2java
 */
@Entity
@Table(name="DauSach_CTPM"
    ,schema="dbo"
    ,catalog="ThuVien"
    ,uniqueConstraints = {@UniqueConstraint(columnNames = {"barcode","maCTPM"})}
)
public class DauSachCtpm  implements java.io.Serializable {

    @Id
    @Column(name="id")
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Integer ma;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "barcode",nullable = false)
    private DauSach dauSach;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "maCTPM",nullable = false)
    private CtPhieumuon cTPhieuMuon;
    
    @OneToMany(mappedBy = "dauSachCtpm",fetch = FetchType.LAZY)
    private Set<CtLoi> ctLois = new HashSet<CtLoi>(0);
    
    public Integer getMa() {
        return this.ma;
    }

    public void setMa(Integer ma) {
        this.ma = ma;
    }

    public DauSach getDauSach() {
        return dauSach;
    }

    public void setDauSach(DauSach dauSach) {
        this.dauSach = dauSach;
    }

    public CtPhieumuon getcTPhieuMuon() {
        return cTPhieuMuon;
    }

    public void setcTPhieuMuon(CtPhieumuon cTPhieuMuon) {
        this.cTPhieuMuon = cTPhieuMuon;
    }
    
    
}


