package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DauSach generated by hbm2java
 */
@Entity
@Table(name="DauSach"
    ,schema="dbo"
    ,catalog="ThuVien"
)
public class DauSach  implements java.io.Serializable {


     private String barcode;
     private Sach sach;
     private Integer tinhTrang;
     private Set<DauSachCtpm> dauSachCtpms = new HashSet<DauSachCtpm>(0);

    public DauSach() {
    }

	
    public DauSach(String barcode) {
        this.barcode = barcode;
    }
    public DauSach(String barcode, Sach sach, Integer tinhTrang, Set<DauSachCtpm> dauSachCtpms) {
       this.barcode = barcode;
       this.sach = sach;
       this.tinhTrang = tinhTrang;
       this.dauSachCtpms = dauSachCtpms;
    }
   
     @Id 

    
    @Column(name="barcode", unique=true, nullable=false, length=10)
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maSach")
    public Sach getSach() {
        return this.sach;
    }
    
    public void setSach(Sach sach) {
        this.sach = sach;
    }

    
    @Column(name="tinhTrang")
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dauSach")
    public Set<DauSachCtpm> getDauSachCtpms() {
        return this.dauSachCtpms;
    }
    
    public void setDauSachCtpms(Set<DauSachCtpm> dauSachCtpms) {
        this.dauSachCtpms = dauSachCtpms;
    }




}


