package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * HinhAnh generated by hbm2java
 */
@Entity
@Table(name="hinh_anh"
    ,schema="dbo"
    ,catalog="libary"
    , uniqueConstraints = @UniqueConstraint(columnNames="src") 
)
public class HinhAnh  implements java.io.Serializable {


     private int id;
     private Sach sach;
     private String src;

    public HinhAnh() {
    }

	
    public HinhAnh(int id) {
        this.id = id;
    }
    public HinhAnh(int id, Sach sach, String src) {
       this.id = id;
       this.sach = sach;
       this.src = src;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maSach")
    public Sach getSach() {
        return this.sach;
    }
    
    public void setSach(Sach sach) {
        this.sach = sach;
    }

    
    @Column(name="src", unique=true, length=100)
    public String getSrc() {
        return this.src;
    }
    
    public void setSrc(String src) {
        this.src = src;
    }




}


