package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loi generated by hbm2java
 */
@Entity
@Table(name="loi"
    ,schema="dbo"
    ,catalog="ThuVien"
)
public class Loi  implements java.io.Serializable {


     private int maLoi;
     private String tenLoi;
     private Set<CtLoi> ctLois = new HashSet<CtLoi>(0);
     private Set<Phat> phats = new HashSet<Phat>(0);

    public Loi() {
    }

	
    public Loi(int maLoi) {
        this.maLoi = maLoi;
    }
    public Loi(int maLoi, String tenLoi, Set<CtLoi> ctLois, Set<Phat> phats) {
       this.maLoi = maLoi;
       this.tenLoi = tenLoi;
       this.ctLois = ctLois;
       this.phats = phats;
    }
   
     @Id 

    
    @Column(name="maLoi", unique=true, nullable=false)
    public int getMaLoi() {
        return this.maLoi;
    }
    
    public void setMaLoi(int maLoi) {
        this.maLoi = maLoi;
    }

    
    @Column(name="tenLoi", length=100)
    public String getTenLoi() {
        return this.tenLoi;
    }
    
    public void setTenLoi(String tenLoi) {
        this.tenLoi = tenLoi;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loi")
    public Set<CtLoi> getCtLois() {
        return this.ctLois;
    }
    
    public void setCtLois(Set<CtLoi> ctLois) {
        this.ctLois = ctLois;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loi")
    public Set<Phat> getPhats() {
        return this.phats;
    }
    
    public void setPhats(Set<Phat> phats) {
        this.phats = phats;
    }




}


