package com.model;
// Generated Jul 17, 2019 3:18:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NhaCungCap generated by hbm2java
 */
@Entity
@Table(name="nhaCungCap"
    ,schema="dbo"
    ,catalog="Libary"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="sdt")} 
)
public class NhaCungCap  implements java.io.Serializable {


     private String maNcc;
     private String tenNcc;
     private String sdt;
     private String email;
     private Set<Sach> saches = new HashSet<Sach>(0);

    public NhaCungCap() {
    }

	
    public NhaCungCap(String maNcc) {
        this.maNcc = maNcc;
    }
    public NhaCungCap(String maNcc, String tenNcc, String sdt, String email, Set<Sach> saches) {
       this.maNcc = maNcc;
       this.tenNcc = tenNcc;
       this.sdt = sdt;
       this.email = email;
       this.saches = saches;
    }
   
     @Id 

    
    @Column(name="maNCC", unique=true, nullable=false, length=6)
    public String getMaNcc() {
        return this.maNcc;
    }
    
    public void setMaNcc(String maNcc) {
        this.maNcc = maNcc;
    }

    
    @Column(name="tenNCC", length=50)
    public String getTenNcc() {
        return this.tenNcc;
    }
    
    public void setTenNcc(String tenNcc) {
        this.tenNcc = tenNcc;
    }

    
    @Column(name="sdt", unique=true, length=10)
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    
    @Column(name="email", unique=true, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhaCungCap")
    public Set<Sach> getSaches() {
        return this.saches;
    }
    
    public void setSaches(Set<Sach> saches) {
        this.saches = saches;
    }




}


