package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PhieuMuon generated by hbm2java
 */
@Entity
@Table(name="phieuMuon"
    ,schema="dbo"
    ,catalog="libary"
)
public class PhieuMuon  implements java.io.Serializable {


     private int maPm;
     private NguoiDung nguoiDungByMaThuThu;
     private NguoiDung nguoiDungByMaNguoiDung;
     private NguoiDung nguoiDungByNguoiNhanTra;
     private int trangThai;
     private Date ngayMuon;
     private Date ngayPhaiTra;
     private Date ngayDat;
     private Date ngayTra;
     private Set<CtPhieumuon> ctPhieumuons = new HashSet<CtPhieumuon>(0);

    public PhieuMuon() {
    }
	
    public PhieuMuon(int maPm, int trangThai) {
        this.maPm = maPm;
        this.trangThai = trangThai;
    }
    public PhieuMuon(int maPm, NguoiDung nguoiDungByMaThuThu, NguoiDung nguoiDungByMaNguoiDung, NguoiDung nguoiDungByNguoiNhanTra, int trangThai, Date ngayMuon, Date ngayPhaiTra, Date ngayDat, Date ngayTra, Set<CtPhieumuon> ctPhieumuons) {
       this.maPm = maPm;
       this.nguoiDungByMaThuThu = nguoiDungByMaThuThu;
       this.nguoiDungByMaNguoiDung = nguoiDungByMaNguoiDung;
       this.nguoiDungByNguoiNhanTra = nguoiDungByNguoiNhanTra;
       this.trangThai = trangThai;
       this.ngayMuon = ngayMuon;
       this.ngayPhaiTra = ngayPhaiTra;
       this.ngayDat = ngayDat;
       this.ngayTra = ngayTra;
       this.ctPhieumuons = ctPhieumuons;
    }
   
     @Id 
      @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="maPM", unique=true, nullable=false)
    public int getMaPm() {
        return this.maPm;
    }
    
    public void setMaPm(int maPm) {
        this.maPm = maPm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maThuThu")
    public NguoiDung getNguoiDungByMaThuThu() {
        return this.nguoiDungByMaThuThu;
    }
    
    public void setNguoiDungByMaThuThu(NguoiDung nguoiDungByMaThuThu) {
        this.nguoiDungByMaThuThu = nguoiDungByMaThuThu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maNguoiDung")
    public NguoiDung getNguoiDungByMaNguoiDung() {
        return this.nguoiDungByMaNguoiDung;
    }
    
    public void setNguoiDungByMaNguoiDung(NguoiDung nguoiDungByMaNguoiDung) {
        this.nguoiDungByMaNguoiDung = nguoiDungByMaNguoiDung;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nguoiNhanTra")
    public NguoiDung getNguoiDungByNguoiNhanTra() {
        return this.nguoiDungByNguoiNhanTra;
    }
    
    public void setNguoiDungByNguoiNhanTra(NguoiDung nguoiDungByNguoiNhanTra) {
        this.nguoiDungByNguoiNhanTra = nguoiDungByNguoiNhanTra;
    }

    
    @Column(name="trangThai", nullable=false)
    public int getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(int trangThai) {
        this.trangThai = trangThai;
    }

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy,HH:mm:ss")
    @Column(name="ngayMuon", length=10)
    public Date getNgayMuon() {
        return this.ngayMuon;
    }
    
    public void setNgayMuon(Date ngayMuon) {
        this.ngayMuon = ngayMuon;
    }

     @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy,HH:mm:ss")
    @Column(name="ngay_Phai_tra", length=10)
    public Date getNgayPhaiTra() {
        return this.ngayPhaiTra;
    }
    
    public void setNgayPhaiTra(Date ngayPhaiTra) {
        this.ngayPhaiTra = ngayPhaiTra;
    }

     @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy,HH:mm:ss")
    @Column(name="ngay_dat", length=10)
    public Date getNgayDat() {
        return this.ngayDat;
    }
    
    public void setNgayDat(Date ngayDat) {
        this.ngayDat = ngayDat;
    }

     @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy,HH:mm:ss")
    @Column(name="ngayTra", length=10)
    public Date getNgayTra() {
        return this.ngayTra;
    }
    
    public void setNgayTra(Date ngayTra) {
        this.ngayTra = ngayTra;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phieuMuon")
    public Set<CtPhieumuon> getCtPhieumuons() {
        return this.ctPhieumuons;
    }
    
    public void setCtPhieumuons(Set<CtPhieumuon> ctPhieumuons) {
        this.ctPhieumuons = ctPhieumuons;
    }




}


