package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PhieuNhap generated by hbm2java
 */
@Entity
@Table(name="phieuNhap"
    ,schema="dbo"
    ,catalog="Libary"
)
public class PhieuNhap  implements java.io.Serializable {


     private int maPhieu;
     private NguoiDung nguoiDung;
     private String ngayTao;
     private Set<CtPhieuNhap> ctPhieuNhaps = new HashSet<CtPhieuNhap>(0);

    public PhieuNhap() {
    }

	
    public PhieuNhap(int maPhieu) {
        this.maPhieu = maPhieu;
    }
    public PhieuNhap(int maPhieu, NguoiDung nguoiDung, String ngayTao, Set<CtPhieuNhap> ctPhieuNhaps) {
       this.maPhieu = maPhieu;
       this.nguoiDung = nguoiDung;
       this.ngayTao = ngayTao;
       this.ctPhieuNhaps = ctPhieuNhaps;
    }
   
     @Id 

    
    @Column(name="maPhieu", unique=true, nullable=false)
    public int getMaPhieu() {
        return this.maPhieu;
    }
    
    public void setMaPhieu(int maPhieu) {
        this.maPhieu = maPhieu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maNguoiDung")
    public NguoiDung getNguoiDung() {
        return this.nguoiDung;
    }
    
    public void setNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }

    
    @Column(name="ngayTao", length=10)
    public String getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(String ngayTao) {
        this.ngayTao = ngayTao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phieuNhap")
    public Set<CtPhieuNhap> getCtPhieuNhaps() {
        return this.ctPhieuNhaps;
    }
    
    public void setCtPhieuNhaps(Set<CtPhieuNhap> ctPhieuNhaps) {
        this.ctPhieuNhaps = ctPhieuNhaps;
    }




}


