package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Rules generated by hbm2java
 */
@Entity
@Table(name="rules"
    ,schema="dbo"
    ,catalog="ThuVien"
    ,uniqueConstraints ={@UniqueConstraint(columnNames = {"nameRules","maNguoiDung"})}
)
public class Rules  implements java.io.Serializable {


     private int id;
     private NguoiDung nguoiDung;
     private String role;

    public Rules() {
    }

	
    public Rules(int id) {
        this.id = id;
    }
    public Rules(int id, String role, NguoiDung nguoiDung) {
       this.id = id;
       this.role = role;
       this.nguoiDung = nguoiDung;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nameRules", length=30)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    @ManyToOne
    @JoinColumn(name = "maNguoiDung",unique = false)
    public NguoiDung getNguoiDung() {
        return nguoiDung;
    }

    public void setNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }

}


