package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sach generated by hbm2java
 */
@Entity
@Table(name="sach"
    ,schema="dbo"
    ,catalog="libary"
    , uniqueConstraints = @UniqueConstraint(columnNames="url") )

public class Sach  implements java.io.Serializable {


     private String maSach;
     private NhaCungCap nhaCungCap;
     private TheLoai theLoai;
     private String tenSach;
     private BigDecimal trongLuong;
     private String loaiBia;
     private Integer soTrang;
     private String kichThuoc;
     private String namXuatBan;
     private Integer gia;
     private Integer soLuong;
     private String url;
     private String ngayTao;
     private Set<LuotThich> luotThiches = new HashSet<LuotThich>(0);
     private Set<Tacgia> tacgias = new HashSet<Tacgia>(0);
     private Set<CtPhieumuon> ctPhieumuons = new HashSet<CtPhieumuon>(0);
     private Set<HinhAnh> hinhAnhs = new HashSet<HinhAnh>(0);
     private Set<DauSach> dauSaches = new HashSet<DauSach>(0);
     private Set<CtPhieuNhap> ctPhieuNhaps = new HashSet<CtPhieuNhap>(0);

    public Sach() {
    }

	
    public Sach(String maSach) {
        this.maSach = maSach;
    }
    public Sach(String maSach, NhaCungCap nhaCungCap, TheLoai theLoai, String tenSach, BigDecimal trongLuong, String loaiBia, Integer soTrang, String kichThuoc, String namXuatBan, Integer gia, Integer soLuong, String url, String ngayTao, Set<LuotThich> luotThiches, Set<Tacgia> tacgias, Set<CtPhieumuon> ctPhieumuons, Set<HinhAnh> hinhAnhs, Set<DauSach> dauSaches, Set<CtPhieuNhap> ctPhieuNhaps) {
       this.maSach = maSach;
       this.nhaCungCap = nhaCungCap;
       this.theLoai = theLoai;
       this.tenSach = tenSach;
       this.trongLuong = trongLuong;
       this.loaiBia = loaiBia;
       this.soTrang = soTrang;
       this.kichThuoc = kichThuoc;
       this.namXuatBan = namXuatBan;
       this.gia = gia;
       this.soLuong = soLuong;
       this.url = url;
       this.ngayTao = ngayTao;
       this.luotThiches = luotThiches;
       this.tacgias = tacgias;
       this.ctPhieumuons = ctPhieumuons;
       this.hinhAnhs = hinhAnhs;
       this.dauSaches = dauSaches;
       this.ctPhieuNhaps = ctPhieuNhaps;
    }
   
     @Id 

    
    @Column(name="maSach", unique=true, nullable=false, length=6)
    public String getMaSach() {
        return this.maSach;
    }
    
    public void setMaSach(String maSach) {
        this.maSach = maSach;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maNhaCungCap")
    public NhaCungCap getNhaCungCap() {
        return this.nhaCungCap;
    }
    
    public void setNhaCungCap(NhaCungCap nhaCungCap) {
        this.nhaCungCap = nhaCungCap;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maTheLoai")
    public TheLoai getTheLoai() {
        return this.theLoai;
    }
    
    public void setTheLoai(TheLoai theLoai) {
        this.theLoai = theLoai;
    }

    
    @Column(name="tenSach", length=50)
    public String getTenSach() {
        return this.tenSach;
    }
    
    public void setTenSach(String tenSach) {
        this.tenSach = tenSach;
    }

    
    @Column(name="trongLuong", precision=6)
    public BigDecimal getTrongLuong() {
        return this.trongLuong;
    }
    
    public void setTrongLuong(BigDecimal trongLuong) {
        this.trongLuong = trongLuong;
    }

    
    @Column(name="loaiBia", length=30)
    public String getLoaiBia() {
        return this.loaiBia;
    }
    
    public void setLoaiBia(String loaiBia) {
        this.loaiBia = loaiBia;
    }

    
    @Column(name="soTrang")
    public Integer getSoTrang() {
        return this.soTrang;
    }
    
    public void setSoTrang(Integer soTrang) {
        this.soTrang = soTrang;
    }

    
    @Column(name="kichThuoc", length=30)
    public String getKichThuoc() {
        return this.kichThuoc;
    }
    
    public void setKichThuoc(String kichThuoc) {
        this.kichThuoc = kichThuoc;
    }

    
    @Column(name="namXuatBan", length=4)
    public String getNamXuatBan() {
        return this.namXuatBan;
    }
    
    public void setNamXuatBan(String namXuatBan) {
        this.namXuatBan = namXuatBan;
    }

    
    @Column(name="gia")
    public Integer getGia() {
        return this.gia;
    }
    
    public void setGia(Integer gia) {
        this.gia = gia;
    }

    
    @Column(name="soLuong")
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }

    
    @Column(name="url", unique=true, length=50)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="ngayTao", length=10)
    public String getNgayTao() {
        return this.ngayTao;
    }
    
    public void setNgayTao(String ngayTao) {
        this.ngayTao = ngayTao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sach")
    public Set<LuotThich> getLuotThiches() {
        return this.luotThiches;
    }
    
    public void setLuotThiches(Set<LuotThich> luotThiches) {
        this.luotThiches = luotThiches;
    }

@ManyToMany(fetch=FetchType.EAGER, mappedBy="saches")
    public Set<Tacgia> getTacgias() {
        return this.tacgias;
    }
    
    public void setTacgias(Set<Tacgia> tacgias) {
        this.tacgias = tacgias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sach")
    public Set<CtPhieumuon> getCtPhieumuons() {
        return this.ctPhieumuons;
    }
    
    public void setCtPhieumuons(Set<CtPhieumuon> ctPhieumuons) {
        this.ctPhieumuons = ctPhieumuons;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="sach")
    public Set<HinhAnh> getHinhAnhs() {
        return this.hinhAnhs;
    }
    
    public void setHinhAnhs(Set<HinhAnh> hinhAnhs) {
        this.hinhAnhs = hinhAnhs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sach")
    public Set<DauSach> getDauSaches() {
        return this.dauSaches;
    }
    
    public void setDauSaches(Set<DauSach> dauSaches) {
        this.dauSaches = dauSaches;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sach")
    public Set<CtPhieuNhap> getCtPhieuNhaps() {
        return this.ctPhieuNhaps;
    }
    
    public void setCtPhieuNhaps(Set<CtPhieuNhap> ctPhieuNhaps) {
        this.ctPhieuNhaps = ctPhieuNhaps;
    }

  

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Sach other = (Sach) obj;
        if (!Objects.equals(this.maSach, other.maSach)) {
            return false;
        }
        if (!Objects.equals(this.tenSach, other.tenSach)) {
            return false;
        }
        if (!Objects.equals(this.loaiBia, other.loaiBia)) {
            return false;
        }
        if (!Objects.equals(this.kichThuoc, other.kichThuoc)) {
            return false;
        }
        if (!Objects.equals(this.namXuatBan, other.namXuatBan)) {
            return false;
        }
        if (!Objects.equals(this.url, other.url)) {
            return false;
        }
        if (!Objects.equals(this.ngayTao, other.ngayTao)) {
            return false;
        }
        if (!Objects.equals(this.nhaCungCap, other.nhaCungCap)) {
            return false;
        }
        if (!Objects.equals(this.theLoai, other.theLoai)) {
            return false;
        }
        if (!Objects.equals(this.trongLuong, other.trongLuong)) {
            return false;
        }
        if (!Objects.equals(this.soTrang, other.soTrang)) {
            return false;
        }
        if (!Objects.equals(this.gia, other.gia)) {
            return false;
        }
        if (!Objects.equals(this.soLuong, other.soLuong)) {
            return false;
        }
        if (!Objects.equals(this.luotThiches, other.luotThiches)) {
            return false;
        }
        if (!Objects.equals(this.tacgias, other.tacgias)) {
            return false;
        }
        if (!Objects.equals(this.ctPhieumuons, other.ctPhieumuons)) {
            return false;
        }
        if (!Objects.equals(this.hinhAnhs, other.hinhAnhs)) {
            return false;
        }
        if (!Objects.equals(this.dauSaches, other.dauSaches)) {
            return false;
        }
        if (!Objects.equals(this.ctPhieuNhaps, other.ctPhieuNhaps)) {
            return false;
        }
        return true;
    }




}


