package com.model;
// Generated Aug 24, 2019 11:38:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tacgia generated by hbm2java
 */
@Entity
@Table(name="tacgia"
    ,schema="dbo"
    ,catalog="Libary"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="sdt")} 
)
public class Tacgia  implements java.io.Serializable {


     private String maTacGia;
     private String hoTen;
     private String diaChi;
     private String email;
     private String sdt;
     private Set<Sach> saches = new HashSet<Sach>(0);

    public Tacgia() {
    }

	
    public Tacgia(String maTacGia) {
        this.maTacGia = maTacGia;
    }
    public Tacgia(String maTacGia, String hoTen, String diaChi, String email, String sdt, Set<Sach> saches) {
       this.maTacGia = maTacGia;
       this.hoTen = hoTen;
       this.diaChi = diaChi;
       this.email = email;
       this.sdt = sdt;
       this.saches = saches;
    }
   
     @Id 

    
    @Column(name="maTacGia", unique=true, nullable=false, length=5)
    public String getMaTacGia() {
        return this.maTacGia;
    }
    
    public void setMaTacGia(String maTacGia) {
        this.maTacGia = maTacGia;
    }

    
    @Column(name="hoTen", length=50)
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="diaChi", length=100)
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    
    @Column(name="email", unique=true, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="sdt", unique=true, length=10)
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="TG_SACH", schema="dbo", catalog="Libary", joinColumns = { 
        @JoinColumn(name="maTacGia", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="maSach", nullable=false, updatable=false) })
    public Set<Sach> getSaches() {
        return this.saches;
    }
    
    public void setSaches(Set<Sach> saches) {
        this.saches = saches;
    }




}


